export const FETCH_OVERFLOW_USERDATA = 'FETCH_OVERFLOW_USERDATA';
export const FETCHING_OVERFLOW_USERDATA = 'FETCHING_OVERFLOW_USERDATA';
export const OVERFLOW_ERROR = 'OVERFLOW_ERROR';

export const FETCH_GITHUB_REPOS = 'FETCH_GITHUB_REPOS';
export const FETCHING_GITHUB_REPOS = 'FETCHING_GITHUB_REPOS';
export const GITHUB_ERROR = 'GITHUB_ERROR';

export const ADD_CURRENT_RECORD = 'ADD_CURRENT_RECORD';